CREATE TABLE TBL_USER_M (
    N_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    S_NAME VARCHAR(100) NOT NULL,
    S_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    S_DEPARTMENT_NAME VARCHAR(100),
    N_SALARY DOUBLE,
    DT_JOINING_DATE DATE,
    S_PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE TBL_ERROR_LOGS (
    N_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DT_CREATED_ON TIMESTAMP,
    S_PATH VARCHAR(255),
    S_ERROR_MESSAGE CLOB,
    N_STATUS INT
);

CREATE TABLE TBL_REFRESH_TOKENS (
    N_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    S_TOKEN_ID VARCHAR(255) NOT NULL UNIQUE,
    S_SECRET_HASH VARCHAR(255) NOT NULL,
    N_USER_ID BIGINT NOT NULL,
    DT_CREATED_AT TIMESTAMP,
    DT_LAST_USED_AT TIMESTAMP,
    DT_EXPIRES_AT TIMESTAMP,
    N_REVOKED BOOLEAN
);


INSERT INTO TBL_USER_M (S_NAME, S_EMAIL, S_DEPARTMENT_NAME, N_SALARY, DT_JOINING_DATE,S_PASSWORD)
VALUES 
  ('Ajay Ingle', 'ajay@gmail.com', 'Engineering', 70000, '2024-01-01','$2a$10$SKnLyEgqivm741VM0s9ycOOGjHizzlM/Vcwq5GWPQmuexYOzgbwTq'),
  ('Pooja Sharma', 'pooja@gmail.com', 'HR', 55000, '2023-07-15','$2a$10$SKnLyEgqivm741VM0s9ycOOGjHizzlM/Vcwq5GWPQmuexYOzgbwTq'),
  ('Rahul Verma', 'rahul@gmail.com', 'Finance', 60000, '2022-03-20','$2a$10$SKnLyEgqivm741VM0s9ycOOGjHizzlM/Vcwq5GWPQmuexYOzgbwTq');