CREATE TABLE TBL_EMPLOYEES_DETAILS (
    N_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    S_NAME VARCHAR(100) NOT NULL,
    S_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    S_DEPARTMENT_NAME VARCHAR(100),
    N_SALARY DOUBLE,
    DT_JOINING_DATE DATE
);

CREATE TABLE TBL_ERROR_LOGS (
    N_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DT_CREATED_ON TIMESTAMP,
    S_PATH VARCHAR(255),
    S_ERROR_MESSAGE CLOB,
    N_STATUS INT
);

INSERT INTO TBL_EMPLOYEES_DETAILS (S_NAME, S_EMAIL, S_DEPARTMENT_NAME, N_SALARY, DT_JOINING_DATE)
VALUES 
  ('Ajay Ingle', 'ajay@gmail.com', 'Engineering', 70000, '2024-01-01'),
  ('Pooja Sharma', 'pooja@gmail.com', 'HR', 55000, '2023-07-15'),
  ('Rahul Verma', 'rahul@gmail.com', 'Finance', 60000, '2022-03-20');